name: pdf_generator_app
description: A Flutter application to convert HTML to PDF.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  open_file: ^3.3.2
  file_selector: ^1.0.0
  url_launcher: ^6.1.12
  file_picker: ^9.2.1
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  screenshot: ^2.1.0
  htmltopdfwidgets: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
